app/login/forms.py
from flask_wtf import FlaskForm
from wtforms import FileField, SubmitField, StringField, PasswordField, SelectField, BooleanField
from wtforms.fields.html5 import DateTimeLocalField, EmailField, IntegerField, TelField, DateField
from wtforms.validators import DataRequired, Length, URL, EqualTo, Email, ValidationError

class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[Email(message="Noa e um email valido"), DataRequired()])
    senha = PasswordField("Senha", validators=[DataRequired()])
    submit = SubmitField("Efetuar Login")


class CadastroUsuario(FlaskForm):
    nome = StringField("Nome", validators=[DataRequired()])
    email = EmailField("Email", validators=[Email(message="Nao eh um email valida"), DataRequired()])
    senha = PasswordField("Senha", validators=[DataRequired()])
    confirmarSenha = PasswordField('Repete Senha', validators=[DataRequired(message='Por favor insira a senha'),
                                                               EqualTo("senha", message="Senhas devem ser iguais"),
                                                               Length(min=5, max=30, message="Senha deve ter no minimo 5 caracteres")])
    sexo = StringField("Sexo", validators=[DataRequired()])
    cpf = StringField("CPF", validators=[DataRequired()])
    tel = TelField("Telefone", validators=[DataRequired()])
    dataNasc = DateField("Data Nascimento", validators=[DataRequired()])
    botaoVolta = SubmitField("Voltar")
    submit = SubmitField("Enviar")                                                               

class Usuario(FlaskForm):
    nome = StringField("Nome", validators=[DataRequired()])
    email = EmailField("Email", validators=[Email(message="Nao eh email valido"), DataRequired()])
    senha = PasswordField("Senha", validators=[DataRequired()])
    confirmarSenha = PasswordField("Repete Senha", validators=[DataRequired(message="Por favor insira a senha"),
                                                               EqualTo("senha", message="Senhas devem ser iguais"),
                                                               Length(min=5, max=30, message="Senha deve ter no minimo 5 caracteres")])
    submit = SubmitField("Enviar")

class Recuperar(FlaskForm):
    email = EmailField("Email", validators=[Email(message="Nao eh um email valido"), DataRequired()])
    botaoVolta = SubmitField("Voltar")
    submit = SubmitField("Enviar")

app/autor/routes.py
from app import login_user, render_template, redirect, url_for, login_required, current_user, request, logout_user, login_manager, Mail, Message, generate_password_hash, flash, Blueprint
# from app.autor.forms import AutoresForm
from app.models.tables import db, Autor, Livros

autor = Blueprint("autor", __name__, template_folder="templates", url_prefix="/autor")


@autor.route('/listarAutores', methods=['GET'])
@login_required
def listar():
    if current_user.is_authenticated:
        autores = Autor.query.all()
        return render_template('autores.html', autores=autores)
    return redirect(url_for('login.logout'))


@autor.route('/inserirAutor', methods=["POST"])
@login_required
def inserirAutor():
    if request.method == "POST":
        nome = request.form["nome"]
        profissao = request.form["profissao"]
        email = request.form["email"]
        endereco = request.form["endereco"]
        autor = Autor(nome=nome, profissao=profissao, email=email, endereco=endereco)
        db.session.add(autor)
        db.session.commit()
        flash("Autor adicionado com sucesso!!!")
        return redirect(url_for('autor.listar'))


@autor.route('excluirAutor/<int:id>', methods=["GET"])
@login_required
def deletarAutor(id):
    if request.method == "GET":
        livrosChecar = Livros.query.all()
        # print(livrosChecar, livrosChecar[0].autor_id)
        for livros in livrosChecar:
            if livros.autor_id == id:
                flash('Desculpe mas esse autor tem publicacoes em livros', category="info")
                return redirect(url_for("autor.listar"))
            
        autor = Autor.query.get(id)
        db.session.delete(autor)
        db.session.commit()
        flash("Autor deletado com sucesso", category="success")
        return redirect(url_for('autor.listar'))
    else:
        flash("Desculpe erro ao excluir autor", category="warning")
        return redirect(url_for('autor.listar'))


@autor.route('/alterarAutor', methods=['GET', 'POST'])
@login_required
def alterarAutor():
    if request.method == 'POST':
        autores = Autor.query.get(request.form.get('id'))
        autores.nome = request.form['nome']
        autores.profissao = request.form['profissao']
        autores.email = request.form['email']
        autores.endereco = request.form['endereco']

        db.session.commit()
        flash('Autor alterado com sucesso!!!')
        return redirect(url_for('autor.listar'))

app/livros/routes.py
from app import login_user, render_template, redirect, url_for, login_required, current_user, request, logout_user, login_manager, Mail, Message, generate_password_hash, flash, Blueprint
# from app.livros.forms import LivrosForms
from app.models.tables import db, Livros, Autor


livros = Blueprint("livros", __name__, template_folder="templates", url_prefix="/livros")


@livros.route('/home', methods=["GET"])
@login_required
def home():
    return render_template('logado.html')


@livros.route('/')
@login_required
def index():
    # dados = Livros.query.get(1).autor
    # dados = Livros.query.order_by(Livros.titulo).all()
    # dados = Livros.query.all()
    # dados = Livros.autores
    # dados = Livros.query.get(1)
    # dados = Livros.query.options(joinedload('editora'))
    # for linha in dados:
    #     print(linha)
    # dados = Livros.query.filter_by(anoPublicacao=2014).first()
    # print(dados.titulo)
    # return render_template('livros.html', livros=dados)

    # autor = Autor(nome="Rafael Seabra", profissao='Professor', email='rafael@gmail.com', endereco='Rua teste 123')
    # db.session.add(autor)
    #
    # #
    # l = Livros(titulo="Quero ficar rico", anoPublicacao=2015, numeroPagina=309, isbn='978-85-452-0122-10', escritor=autor)
    # db.session.add(l)
    # db.session.commit()
    # #
    #
    # # editora = Editora(nome='Gente', endereco='Rua da gente como gente', telefone='2093012932', email='gente@gmail.com' , site='gente@gente.com', cep='2039201', editora=l)
    # # db.session.add(editora)
    #
    # db.session.commit()
    # livros = Livros.query.order_by(Livros.id).all()  # trazer todos os registros
    # livros = Livros.query.order_by(Livros.autor).all()
    livros = Livros.query.all()
    # autor = Autor.query.all()
    # autores = Autor.query.all()
    # print(livros.anoPublicacao)
    # print(autor.nome)
    for lista in livros:
        print("{} | {} | {}".format(lista.titulo, lista.id, lista.escritor.email))  # iterar em cima da lista
    # print(livros.numeroPagina)
    autores = Autor.query.all()
    # print(autores[0])
    # for lista in autores:
    #     print("{} | {} | {} | {} | {}".format(lista.autor.titulo, lista.id, lista.nome, lista.autor.anoPublicacao,
    #                                           lista.autor.numeroPagina))

    return render_template('livros.html', livros=livros, autores=autores)

@livros.route('/inserir', methods=["POST"])
@login_required
def inserir():
    if request.method == "POST":
        titulo = request.form["titulo"]
        anoPublicacao = request.form["anoPublicacao"]
        numeroPagina = request.form["numeroPagina"]
        isbn = request.form["isbn"]
        autor = request.form["autor"]
        # editora = request.form["editora"]

        livros = Livros(titulo=titulo, anoPublicacao=anoPublicacao, numeroPagina=numeroPagina, isbn=isbn,
                        autor_id=autor)
        db.session.add(livros)
        db.session.commit()
        flash('Livros adicionados com sucesso')
        return redirect(url_for('livros.index'))


@livros.route('/alterar', methods=["GET", "POST"])
@login_required
def alterar():
    if request.method == "POST":
        livros = Livros.query.get(request.form.get('id'))
        livros.titulo = request.form["titulo"]
        livros.anoPublicacao = request.form["anoPublicacao"]
        livros.numeroPagina = request.form["numeroPagina"]
        livros.isbn = request.form["isbn"]
        livros.autor_id = request.form["autor"]
        # livros.editora = request.method["editora"]

        db.session.commit()
        flash('Livros alterados com sucesso')
        return redirect(url_for('livros.index'))


@livros.route('/deletar/<int:id>', methods=["GET"])
@login_required
def deletar(id):
    livros = Livros.query.get(id)
    # livros = Livros.query.filter_by(id=id).first()
    db.session.delete(livros)
    db.session.commit()
    flash("Livro excluido com sucesso!!!")
    return redirect(url_for('livros.index'))

app/login/routes.py
from app import login_user, render_template, redirect, url_for, login_required, current_user, request, logout_user, login_manager, Mail, Message, generate_password_hash, flash, Blueprint
from app.login.forms import LoginForm, Usuario, CadastroUsuario, Recuperar
from app.models.tables import db, User
import random
import string

login = Blueprint('login', __name__, template_folder='templates', url_prefix='/login')

login_manager.login_view = "login.verificaLogin"
login_manager.login_message = "Por favor se autenticar antes de acessar o sistema!!!"
login_manager.login_message_category = "info"
login_manager.refresh_view = "login.index"
login_manager.needs_refresh_message = (u"Para proteger sua conta, por favor reautentique para acessar a pagina")
login_manager.needs_refresh_message_category = "info"


@login.route("/recuperar", methods=["GET", "POST"])
def recuperar():
    forms = Recuperar()
    if forms.validate_on_submit():
        print(forms.email.data)
        email = Usuario.query.filter_by(email=forms.email.data).first()
        

@login.route('/register', methods=["GET", "POST"])
def register():
    if request.method == "POST":
        nome = request.form['nome']
        email = request.form['email']
        senha = request.form['senha']

        user = User(nome, email, senha)
        db.session.add(user)
        db.session.commit()
        # return redirect(url_for('register'))
    return render_template('register.html')


@login.route('/login', methods=["GET", "POST"])
def verificaLogin():
    if request.method == "POST":
        email = request.form['email']
        senha = request.form['senha']

        user = User.query.filter_by(email=email).first()

        if not user or not user.verifica_senha(
                senha):  # verificando se o usuario nao existir e nao tiver senha redireciona para a tela de login senao efetua o login
            flash('Verifique email ou senha!!!')
            return redirect(url_for('login.verificaLogin'))

        # if current_user.is_authenticated:
        #     login_user(user, remember=True)
        #     return redirect(url_for('listar'))
        # else:
        #     login_user(None)
        login_user(user, remember=True)
        return redirect(url_for('livros.index'))

    return render_template('login.html')


@login.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('login.verificaLogin'))

app/templates/autores.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron p-3">
                <h2> Autores <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#mymodal">Adicionar novos autores </button></h2>
            </div>


            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for mensagens in messages %}
                        <div class="alert alert-success alert-dismissable" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">x</span>
                            </button>
                            {{ mensagens }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            <table class="table table-hover table-dark">
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Profissão</th>
                    <th>Email</th>
                    <th>Endereço</th>
                    <th>Açoes</th>
                </tr>


                {% for linhas in autores %}
                    <tr>

                        <td>{{ linhas.id }}</td>
                        <td>{{ linhas.nome }}</td>
                        <td>{{ linhas.profissao }}</td>
                        <td>{{ linhas.email }}</td>
                        <td>{{ linhas.endereco }}</td>

                        <td>
                            <a href="/alterarAutor/{{ linhas.id }}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{ linhas.id }}">Editar</a>
                            <a href="excluirAutor/{{ linhas.id }}" class="btn btn-danger tbn-xs" onclick="return confirm('Deseja realmente deletar o autor??')">Excluir</a>
                        </td>
                    </tr>

                    <div id="modaledit{{linhas.id}}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Alterar Autor </h4>
                                </div>

                                <div class="modal-body">
                                    <form action="{{url_for('autor.alterarAutor')}}" method="POST">
                                        <div class="form-group">
                                            <label>Nome</label>
                                            <input type="hidden" name="id" value="{{ linhas.id }}">
                                            <input type="text" class="form-control" name="nome" value="{{ linhas.nome }}">
                                        </div>

                                        <div class="form-group">
                                            <label>Profissão</label>
                                            <input type="text" class="form-control" name="profissao" value="{{ linhas.profissao }}">
                                        </div>

                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="email" class="form-control" name="email" value="{{ linhas.email }}">
                                        </div>

                                        <div class="form-group">
                                            <label>Endereco</label>
                                            <input type="text" class="form-control" name="endereco" value="{{ linhas.endereco }}">
                                        </div>

                                        <div class="form-group pt-2">
                                            <button class="btn btn-primary" type="submit">Alterar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </table>
        </div>

        <div id="mymodal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title"> Adicionar Autor </h4>
                    </div>

                    <div class="modal-body">
                        <form action="{{ url_for('autor.inserirAutor') }}" method="POST">
                            <div class="form-group">
                                <label> Nome: </label>
                                <input type="text" class="form-control" name="nome" required="1">
                            </div>

                            <div class="form-group">
                                <label> Profissão: </label>
                                <input type="text" class="form-control" name="profissao" required="1">
                            </div>

                            <div class="form-group">
                                <label> Email: </label>
                                <input type="email" class="form-control" name="email" required="1">
                            </div>

                            <div class="form-group">
                                <label> Endereço: </label>
                                <input type="endereco" class="form-control" name="endereco" required="1">
                            </div>

                            <div class="form-group pt-2">
                                <button class="btn btn-primary" type="submit">Adicionar Autor</button>
                            </div>
                        </form>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Fechar</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


{% endblock %}

app/templates/formUploads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for mensagens in messages %}
                 <div class="alert alert-success alert-dismissable" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="close">
                           <span aria-hidden="true">x</span>
                      </button>
                      {{ mensagens }}
                 </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form method="POST" enctype="multipart/form-data">
       {# {{ formObj.csrf_token}} #}
       {# {{ formObj.image }} #}
        <input type=file name=file>
        <button type="submit"> Upload </button>

    </form>
</body>
</html>

app/templates/gas.html
{% include 'base.html' %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-hover table-dark">
                  <tr>
                      <th>ID</th>
                      <th>VALOR</th>
                      <th>HORA</th>
                  </tr>
     {% for linha in gas %}
        <tr>
            <td>{{ linha.id }}</td>
            <td>{{ linha.valorMedido }}</td>
            <td>{{ linha.horasMedicao }}</td>
            <td>
              <a href="/alterar/{{linha.id}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{linha.id}}">Editar</a>
              <a href="/deletar/{{linha.id}}" class="btn btn-danger btn-xs" onclick="return confirm('Deseja realmente deletar o item?')">Deletar</a>
            </td>
        </tr>
     {% endfor %}
 </table>

        </div>
    </div>
</div>


<script>
    setInterval(function() { window.location.href = "http://192.168.0.6:59000" }, 15000);
</script>




{% for linha in gas %}
            {{ linha.id }}
            {{ linha.valorMedido }}
            {{ linha.horasMedicao }}
{% endfor %}


app/templates/livros.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block body %}


<div class="container">
    <div class="row">
          <div class="col-md-12">

              <div class="jumbotron p-3">
                  <h2> Livros <button type="button" class="btn btn-success float-right" data-toggle="modal" data-target="#mymodal"> Adicionar novos livros</button> </h2>
              </div>


              {% with mensagens = get_flashed_messages() %}
                  {% if mensagens %}
                      {% for mensagem in mensagens %}
                           <div class="border border-success alert alert-success alert-dismissable" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                   <span aria-hidden="true">x</span>
                                </button>
                                <h5>{{ mensagem }}</h5>
                           </div>
                      {% endfor %}
                  {% endif %}
              {% endwith %}

              <table class="table table-hover table-dark">
                  <tr>
                      <th>ID</th>
                      <th>Titulo</th>
                      <th>Ano Publicação</th>
                      <th>Numero Pagianas </th>
                      <th>ISBN</th>
                      <th>Autor</th>
                      <th>Ação</th>
                  </tr>


                  {% for l in livros %}
                       <tr>
                           <td>{{ l.id }}</td>
                           <td>{{ l.titulo }}</td>
                           <td>{{ l.anoPublicacao }}</td>
                           <td>{{ l.numeroPagina }}</td>
                           <td>{{ l.isbn }}</td>
                           <td>{{ l.escritor.nome }}</td>

                           <td>
                               <a href="/alterar/{{l.id}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{l.id}}">Editar</a>
                               <a href="deletar/{{l.id}}" class="btn btn-danger btn-xs" onclick="return confirm('Deseja realmente deletar o item?')">Deletar</a>
                           </td>
                       </tr>

                      <div id="modaledit{{l.id}}" class="modal fade" role="dialog">
                          <div class="modal-dialog">
                              <div class="modal-content">
                                  <div class="modal-header">
                                      <h4 class="modal-title">Alterar informação </h4>
                                  </div>

                                  <div class="modal-body">
                                      <form action="{{url_for('livros.alterar')}}" method="POST">
                                          <div class="form-group">
                                              <label>Titulo: </label>
                                              <input type="hidden" name="id" value="{{ l.id }}">
                                              <input type="text" class="form-control" name="titulo" value="{{ l.titulo }}">
                                          </div>

                                          <div class="form-group">
                                              <label>Ano Publicacao: </label>
                                              <input type="text" class="form-control" name="anoPublicacao" value="{{ l.anoPublicacao }}">
                                          </div>

                                          <div class="form-group">
                                              <label>Numero Paginas: </label>
                                              <input type="number" class="form-control" name="numeroPagina" value="{{ l.numeroPagina}}">
                                          </div>

                                          <div class="form-group">
                                              <label>ISBN: </label>
                                              <input type="text" class="form-control" name="isbn" value="{{ l.isbn}}">
                                          </div>

                                            <label>Autores: </label>
                                                <select class="form-control" name="autor">
                                                    {% for linhas in autores %}
                                                        <option value="{{ linhas.id }}"  {% if linhas.id == l.escritor.id %} selected="selected" {% endif %}>
                                                             {{ linhas.nome }}
                                                        </option>
                                                    {% endfor %}
                                                </select>


                                          <div class="form-group pt-2">
                                              <button class="btn btn-primary" type="submit">Alterar</button>
                                          </div>

                                      </form>
                                  </div>
                                  <div class="modal-footer">
                                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                  </div>
                              </div>
                          </div>
                      </div>
                  {% endfor %}
              </table>
          </div>

        <div id="mymodal" class="modal fade" role="dialog">
              <div class="modal-dialog">
                   <div class="modal-content">
                       <div class="modal-header">
                           <h4 class="modal-title">Adicionar Livros</h4>
                       </div>

                       <div class="modal-body">
                           <form action="{{url_for('livros.inserir')}}" method="POST">
                                <div class="form-group">
                                   <label>Titulo: </label>
                                   <input type="hidden">
                                   <input type="text" class="form-control" name="titulo" required="1">
                                </div>

                                <div class="form-group">
                                   <label>Ano Publicacao: </label>
                                   <input type="text" class="form-control" name="anoPublicacao" required="1">
                                </div>

                                <div class="form-group">
                                  <label>Numero Paginas: </label>
                                  <input type="number" class="form-control" name="numeroPagina" required="1">
                                </div>

                                <div class="form-group">
                                   <label>ISBN: </label>
                                   <input type="text" class="form-control" name="isbn" required="1">
                                </div>

                               <label>Autores: </label>
                               <select class="form-control" name="autor">
                                   {% for linhas in autores %}
                                        <option value="{{ linhas.id}}"> {{ linhas.nome }}</option>
                                   {% endfor %}
                               </select>

                                <div class="form-group pt-2">
                                    <button class="btn btn-primary" type="submit">Adicionar Livros </button>
                                </div>
                           </form>
                        </div>

                       <div class="modal-footer">
                           <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                       </div>
                   </div>
              </div>
        </div>

    </div>
</div>


{% for autor in autores %}
    <option value="{{autor.id}}">{{ autor.nome }}</option>
{% endfor %}


{% endblock %}

app/templates/logado.html

<!--{% if current_user.nome != none %}-->
<!--    <div>-->
<!--        <h1>{{ current_user.nome }}</h1>-->
<!--        <p>Esse texto aparece caso você esteja logado</p>-->
<!--    </div>-->
<!--{% elif current_user.nome == none %}-->
<!--    <div>-->
<!--        <h1>Visitante</h1>-->
<!--        {{ current_user.nome }}-->
<!--        <p>Esse texto aparece caso você não esteja logado</p>-->
<!--    </div>-->
<!--{% endif %}-->

app/templates/login.html
{% extends 'base.html' %}

{% block body %}



<div class="container text-center">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <form action="" method="POST" class="form-signin">
                <h1 class="h2 mb-2 display-4 font-weight-normal pb-3">Login</h1>

                    {% with mensagens = get_flashed_messages() %}
                        {% if mensagens %}
                            {% for message in mensagens %}
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="border border-success alert alert-success alert-dismissable" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                                <span aria-hidden="true">x</span>
                                            </button>
                                            <h5><span class="oi oi-check" aria-hidden="true"></span> {{ message }}</h5>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}


                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" name="email" placeholder="teste@hotmail.com" required autofocus>
                </div>
                <div class="form-group">
                    <label for="senha">Senha</label>
                    <input type="password" class="form-control" name="senha" placeholder="teste321@" required>
                </div>
                <div class="form-group">
                    <label>
                        <a href="{{url_for('login.register')}}">Se ainda não tem login, clique aqui para se registrar!!!</a>
                    </label>
                </div>
                <button type="submit" class="btn btn-block btn-primary"><span class="oi oi-account-login" title="icon name" aria-hidden="true"></span> Enviar </button>
                <p class="mt-5 mb-3 text-muted">&copy; 2020</p>
            </form>
        </div>
    </div>
</div>

<script>

    window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).slideUp(500,
        function(){
            $(this).remove();
        });
     }, 2000);
</script>


{% endblock %}

app/templates/register.html
<form action="" method="POST">
    <input type="text" name="nome">
    <input type="email" name="email">
    <input type="password" name="senha">
    <input type="submit" value="cadastrar">
</form>